### PR TITLE
Improved naming convention to avoid conflicts

### PR DESCRIPTION
**Pull request by fr-josh**
This project is great and I have found it very useful. Thanks for the great work.

One small problem I have encountered is how how generic the names of the structs and enums are. Location and Mode have often conflicted with my projects and other Pods due to having commonly used names.

I thought it would be useful to refactor the names of the structs and enums to avoid these conflicts. This is slightly a personal preferences so feel free to decline this PR.

### CODE REVIEW

**Comment by kiliankoe** [comment]
I totally understand where you're coming from and I definitely appreciate the effort, but using name prefixes feels so *objc-esque*, since swift makes it possible to refer to `Karte.Location`, `Karte.Mode` and `Karte.App` and should then (if I'm not mistaken) not encounter any ambiguity when your types with the same names are in your module's namespace.

On the other hand, that does make it a bit more cumbersome to use this library, so I'm not entirely decided in one direction or the other 🙈

**Comment by fr-josh** [comment]
I completely agree with everything you've said. It's probably my Obj-C habits creeping into my thought processes.

I happy either way so maybe stick with the Swifty way, alway best to stick with the future / more than happy for you to make a call either way 🙂

**Comment by kiliankoe** [comment]
If it's not too much of a hassle to possibly namespace the types I think I'll prefer to keep it the way it is. Thanks again though for your input and the PR! It's much appreciated!

**Comment by fr-josh** [comment]
No worries at all! Great project! If I come across anything else I’ll happily PR 👍🏻

**Pull request closed without merging**
